spring:
  application.name: AccountService
  profiles.active: dev
  security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9000

products.openapi:
  dev-url: http://www.dev.microcompany.es
  prod-url: http://www.prod.microcompany.es

---

spring:
  profiles: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:accounts_db"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900

logging:
  level.root: INFO
  file.name: /tmp/logs/mylog.log


---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_db
    username: account_user
    password: acc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

server:
  port: 9943
  ssl:
    key-store: keystore2.p12
    key-store-password: abc123.
    keyStoreType: PKCS12
    keyAlias: tomcat